In [1]:
#import pandas with alias pd
import pandas as pd

In [6]:
#read csv file
top_50 = pd.read_csv('./datasets/spotify-streaming-top-50-world.csv')

In [7]:
# read the first 5 
top_50.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
0,2023-05-18,1,Ella Baila Sola,Eslabon Armado,89,165671,album,16,2023-04-28,False,https://i.scdn.co/image/ab67616d0000b273dfddf1...
1,2023-05-18,2,un x100to,Grupo Frontera & Bad Bunny,99,194563,single,1,2023-04-17,False,https://i.scdn.co/image/ab67616d0000b273716c0b...
2,2023-05-18,3,La Bebe - Remix,Yng Lvcas & Peso Pluma,99,234352,single,2,2023-03-17,True,https://i.scdn.co/image/ab67616d0000b273a04be3...
3,2023-05-18,4,Cupid - Twin Ver.,FIFTY FIFTY,97,174253,single,3,2023-02-24,False,https://i.scdn.co/image/ab67616d0000b27337c0b3...
4,2023-05-18,5,Flowers,Miley Cyrus,91,200600,album,13,2023-03-10,False,https://i.scdn.co/image/ab67616d0000b27358039b...

In [8]:
#read the last 10 rows
top_50.tail(10)

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,release_date,is_explicit,album_cover_url
16840,2024-04-20,41,Starboy,The Weeknd,92,230453,album,18,2016-11-25,True,https://i.scdn.co/image/ab67616d0000b2734718e2...
16841,2024-04-20,42,I Remember Everything (feat. Kacey Musgraves),Zach Bryan,92,227195,album,16,2023-08-25,False,https://i.scdn.co/image/ab67616d0000b273e5a25e...
16842,2024-04-20,43,Another Love,Tom Odell,66,244360,album,10,2013-06-17,True,https://i.scdn.co/image/ab67616d0000b2731b51f8...
16843,2024-04-20,44,Whatever She Wants,Bryson Tiller,90,161342,single,1,2024-02-13,True,https://i.scdn.co/image/ab67616d0000b2731aba7b...
16844,2024-04-20,45,Slow It Down,Benson Boone,84,161831,album,15,2024-04-05,False,https://i.scdn.co/image/ab67616d0000b273cc04ff...
16845,2024-04-20,46,Training Season,Dua Lipa,92,209487,single,4,2024-02-15,False,https://i.scdn.co/image/ab67616d0000b273790260...
16846,2024-04-20,47,Houdini,Dua Lipa,92,185917,single,1,2023-11-09,False,https://i.scdn.co/image/ab67616d0000b273001d57...
16847,2024-04-20,48,PERRO NEGRO,Bad Bunny,92,162767,album,22,2023-10-13,True,https://i.scdn.co/image/ab67616d0000b2737b1fc5...
16848,2024-04-20,49,Evergreen,Richy Mitch & The Coal Miners,90,87000,album,14,2017-05-17,False,https://i.scdn.co/image/ab67616d0000b2731cc17b...
16849,2024-04-20,50,QLONA,KAROL G,90,172797,album,9,2023-08-10,True,https://i.scdn.co/image/ab67616d0000b273d026bf...

In [9]:
# Get the number of rows and columns in this csv
top_50.shape

(16850, 11)

In [10]:
#Get information on all the columns
top_50.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16850 entries, 0 to 16849
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             16850 non-null  object
 1   position         16850 non-null  int64
 2   song             16850 non-null  object
 3   artist           16850 non-null  object
 4   popularity       16850 non-null  int64
 5   duration_ms      16850 non-null  int64
 6   album_type       16850 non-null  object
 7   total_tracks     16850 non-null  int64
 8   release_date     16850 non-null  object
 9   is_explicit      16850 non-null  bool
 10  album_cover_url  16850 non-null  object
dtypes: bool(1), int64(4), object(6)
memory usage: 1.3+ MB

In [11]:
#Get the mean, std and others from the csv
top_50.describe()

           position    popularity    duration_ms  total_tracks
count  16850.000000  16850.000000   16850.000000  16850.000000
mean      25.500000     90.232819  196721.617864     10.714896
std       14.431298     11.323718   39443.918462      9.018766
min        1.000000      0.000000   42166.000000      1.000000
25%       13.000000     89.000000  172797.000000      1.000000
50%       25.500000     93.000000  194857.000000     12.000000
75%       38.000000     95.000000  222369.000000     16.000000
max       50.000000    100.000000  405906.000000    119.000000